apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-travel-planner
  labels:
    app: travel-planner
spec:
  replicas: 2
  selector:
    matchLabels:
      app: travel-planner
  template:
    metadata:
      labels:
        app: travel-planner
    spec:
      containers:
        - name: travel-planner-container
          image: ai-travel-planner:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: ENVIRONMENT
              value: "production"
          envFrom:
            - secretRef:
                name: travel-planner-secrets
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: travel-planner-service
  labels:
    app: travel-planner
spec:
  type: LoadBalancer
  selector:
    app: travel-planner
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      name: http

